
export const CART_CREATE_REQUEST = "CART_CREATE_REQUEST";
export const CART_CREATE_SUCCESS = "CART_CREATE_SUCCESS";
export const CART_CREATE_FAILURE = "CART_CREATE_FAILURE";

export const CART_FIND_USER_REQUEST = "CART_FIND_USER_REQUEST";
export const CART_FIND_USER_SUCCESS = "CART_FIND_USER_SUCCESS";
export const CART_FIND_USER_FAILURE = "CART_FIND_USER_FAILURE";

export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAILURE = "CART_ADD_ITEM_FAILURE";

export const CART_UPDATE_ITEM_REQUEST = "CART_UPDATE_ITEM_REQUEST";
export const CART_UPDATE_ITEM_SUCCESS = "CART_UPDATE_ITEM_SUCCESS";
export const CART_UPDATE_ITEM_FAILURE = "CART_UPDATE_ITEM_FAILURE";

export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAILURE = "CART_REMOVE_ITEM_FAILURE";

export const CART_CLEAR = "CART_CLEAR";