export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILED  = "CREATE_PRODUCT_FAILED";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED  = "UPDATE_PRODUCT_FAILED";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED  = "DELETE_PRODUCT_FAILED";

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILED  = "GET_ALL_PRODUCTS_FAILED";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILED  = "GET_PRODUCT_BY_ID_FAILED";

export const GET_HOT_DEALS_REQUEST = "GET_HOT_DEALS_REQUEST";
export const GET_HOT_DEALS_SUCCESS = "GET_HOT_DEALS_SUCCESS";
export const GET_HOT_DEALS_FAILED  = "GET_HOT_DEALS_FAILED";

export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST";
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_BY_CATEGORY_SUCCESS";
export const GET_PRODUCTS_BY_CATEGORY_FAILED  = "GET_PRODUCTS_BY_CATEGORY_FAILED";

export const GET_RELATED_PRODUCTS_REQUEST = "GET_RELATED_PRODUCTS_REQUEST";
export const GET_RELATED_PRODUCTS_SUCCESS = "GET_RELATED_PRODUCTS_SUCCESS";
export const GET_RELATED_PRODUCTS_FAILED  = "GET_RELATED_PRODUCTS_FAILED";

export const CLEAR_PRODUCT_ERRORS = "CLEAR_PRODUCT_ERRORS";
